articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article

# class ArticleForm(forms.Form)
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content',]

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Article
from .forms import ArticleForm

def index(request):
    # Article.objects.all()[::-1] -> Python
    articles = Article.objects.order_by('-pk') # Query문이 다름
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        # request.POST -> QueryDict
        # 변수 이름 = 클래스()  -> 클래스로부터 인스턴스 생성
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        # 비어있는 form
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/form.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # article = Article.objects.get(pk=article_pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

# 주소창을 통해 ->  articles/2/delete/ -> GET
@require_POST
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    article.delete()
    return redirect('articles:index')

def update(request, article_pk):
    # 공통으로 사용
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        # request.POST -> QueryDict / article -> 기존 글
        # instance=article을 안넣어주면? -> 새로운 글이 작성됨
        form = ArticleForm(request.POST, instance=article)
        # print(form)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        # 기존에 사용자가 작성한 글이 포함된 == instance=article
        # Form
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/form.html', context)

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>상세 글</h2>
    <h3>{{ article.pk }}번글 : {{ article.title }}</h3>
    <p>글 내용: {{ article.content }}</p>
    <p>글 생성 시각: {{ article.created_at }}</p>
    <p>글 수정 시각: {{ article.updated_at }}</p>
    <hr>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글 삭제">
    </form>
    <a href="{% url 'articles:update' article.pk %}"><button>글 수정</button></a>
    <a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}

{% block content %}
    {% if request.resolver_match.url_name == 'create' %}
        <h2>글 생성</h2>
    {% else %}
        <h2>글 수정</h2>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="작성">
    </form>

    {% if request.resolver_match.url_name == 'create' %}
        <a href="{% url 'articles:index' %}">BACK</a>
    {% else %}
        <a href="{% url 'articles:detail' article.pk %}">BACK</a>
    {% endif %}

{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>메인 페이지</h2>
    <a href="{% url 'articles:create' %}">글 쓰러가기</a>
    <hr>
    {% for article in articles %}
        <h3>글 번호: {{ article.pk }}</h3>
        <h3>글 제목: {{ article.title }}</h3>
        <a href="{% url 'articles:detail' article.pk %}">상세 글 보러가기</a>
        <hr>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>exercise & homework</title>
</head>
<body>
    <h1>CRUD with ModelForm</h1>
    {% block content %}
    {% endblock %}
</body>
</html>